server:
  port: 8005
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowableTest?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: 123456
flowable:
  async-executor-activate: false
